platform :ios, '7.0'

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

pod 'AFNetworking/Serialization', '2.5.0'
pod 'AFNetworking/Security', '2.5.0'
pod 'AFNetworking/Reachability', '2.5.0'
pod 'AFNetworking/NSURLConnection', '2.5.0'
pod 'AFNetworking/NSURLSession', '2.5.0'

pod ’YYCache‘


